//USER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
//UI TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
//DASHBOARD TYPES
export const SET_DASHBOARD = 'SET_DASHBOARD';
export const LOADING_DASHBOARD = 'LOADING_DASHBOARD';
export const SAVE_DASHBOARD = 'SAVE_DASHBOARD';
export const CLEAR_DASHBOARD = 'CLEAR_DASHBOARD';
